name: Auto Deploy to My Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /opt/vue3-shopper
          git pull origin main
          /opt/node16/bin/npm install
          /opt/node16/bin/npm run build-only
          pm2 reload all || pm2 start dist/server.js --name vue-shop-api


