name: Deploy to Aliyun

on:
  push:
    branches:
      - main  # ⚠️ 如果你主分支叫 master 就改成 master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: "/www/wwwroot/dist"
